# Generated by Django 5.0.6 on 2024-07-03 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_player_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tips', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='baseline_exercise_pics/')),
                ('training_target', models.CharField(choices=[('strength', 'Strength'), ('endurance', 'Endurance'), ('agility', 'Agility'), ('sprint', 'Sprint'), ('shooting', 'Shooting'), ('passing', 'Passing'), ('header', 'Header')], max_length=100)),
                ('type', models.CharField(choices=[('repetitions', 'Repetitions'), ('time', 'Time'), ('success_rate', 'Success Rate')], max_length=20)),
                ('repetitions', models.IntegerField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, null=True)),
                ('max_success_rate', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='BaselinePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successful_attempts', models.IntegerField(blank=True, null=True)),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.baselineexercise')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.FloatField(default=0)),
                ('endurance', models.FloatField(default=0)),
                ('agility', models.FloatField(default=0)),
                ('sprint', models.FloatField(default=0)),
                ('shooting', models.FloatField(default=0)),
                ('passing', models.FloatField(default=0)),
                ('header', models.FloatField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('max_score', models.IntegerField(default=10)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.baselineexercise')),
            ],
        ),
    ]
