# Generated by Django 5.0.6 on 2024-07-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_baselineexercise_baselineperformance_playerrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselineexercise',
            name='advanced_criteria',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='baselineexercise',
            name='beginner_criteria',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='baselineexercise',
            name='intermediate_criteria',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='baselineperformance',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
