# Generated by Django 5.0.6 on 2024-07-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_alter_baselineexercise_max_success_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselineperformance',
            name='repetitions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
