# Generated by Django 5.0.6 on 2024-07-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_baselineperformance_repetitions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baselineexercise',
            old_name='max_success_rate',
            new_name='attempts',
        ),
    ]
