# Generated by Django 5.0.6 on 2024-07-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_rename_max_success_rate_baselineexercise_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baselineexercise',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='baselineexercise',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='baselineexercise',
            name='time',
        ),
    ]
