# Generated by Django 5.0.6 on 2024-07-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_remove_baselineexercise_attempts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baselineperformance',
            old_name='time_taken',
            new_name='time',
        ),
        migrations.DeleteModel(
            name='ProTarget',
        ),
    ]
